version: "3.8"

services:
  nginx:
    image: ghcr.io/alexbidenko1998/faraday-frontend/nginx:latest
    expose:
      - 4000
    volumes:
      - nginx-cache:/data/nginx/cache
    networks:
      - server
      - internal
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  application:
    image: ghcr.io/alexbidenko1998/faraday-frontend/application:latest
    expose:
      - 3000
    networks:
      - internal
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

volumes:
  nginx-cache:

networks:
  server:
    external: true
  internal:
